---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbpod
  labels:
    app: facebook
    env: sbox
spec:
  selector:
   matchLabels:
     app: facebook
  replicas: 3
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
        env: sbox
        version: AC_V1
    spec:
      containers:
        - name: fbcont
          image: nikhhel/nikhhel:httpdc1
          ports:
            - containerPort: 8080

    